services:
  app:
    image: ramiro/node-locations-app
    ports:
      - "8080:8080"
    environment:  
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_SERVICE_URL: db
      MONGO_PORT: 27017
      MONGO_DB_NAME: test
      PORT: 8080
      CACHE_TTL: 15
      TOKEN_TTL: 200s
      TOKEN_SECRET: pescado
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example