services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./environments/mongo.env
    volumes:
      - "./data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  app:
    build: .
    image: ramiro/node-locations-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./environments/app.env
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_SERVICE_URL: db
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      PORT: ${PORT}
      CACHE_TTL: ${CACHE_TTL}
      TOKEN_TTL: ${TOKEN_TTL}
      TOKEN_SECRET: ${TOKEN_SECRET}